---
# This playbook configures the guest OS as Vagrant creates the VMs.
- name: Common configuration
  hosts: all
  roles:
    - role: common

- name: Configure Network Manager connections
  hosts: nmhosts
  roles:
    - role: nmhost

- name: Server with GUI
  hosts: servers_with_gui
  roles:
    - role: server-with-gui

- name: FTP Servers
  hosts: ftp_servers
  roles:
    - role: ftp-server

- name: NFS Servers
  hosts: nfs_servers
  roles:
    - role: nfs-server

- name: Samba Servers
  hosts: samba_servers
  roles:
    - role: samba-server

# - name: IdM Servers
#   hosts: idm_servers
#   roles:
#     - role: idm-server
#     - role: idm-users
#     - role: idm-automounts

- name: Configure access to labfiles from within the VM
  hosts: labhosts
  roles:
    - role: labhost

- name: Exam hosts
  hosts: examhosts
  roles:
    - role: examhost
