#!/bin/bash
# This script installs Ansible if on MacOSX and it is not already installed and
# then runs the playbook to configure the virtualization software on the host.

# We install ansible using pip on MacOSX but assume it is installed on Linux
# via native packages.
if [[ "Darwin" == "$(uname)" ]]; then
  which ansible-playbook
  if [[ $? -ne 0 ]]; then
    sudo -H python3 /usr/local/bin/easy_install pip &&
    sudo -H pip install ansible
  fi
fi

cd ./.setup && ansible-playbook -K -i localhost, -c local --skip-tags disabled setup.yml
