---
- name: Configure server1 as a yum repo
  gather_facts: false
  hosts:
    - server1
  tasks:
    - block:
        - name: Ensure packages are installed
          ansible.builtin.yum:
            name: "{{ packages }}"
            state: present
          vars:
            packages:
              - nginx
              - createrepo
          register: pkgadd
        - name: Ensure web server is started and enabled
          ansible.builtin.systemd:
            name: nginx
            enabled: yes
            state: started
        - name: Ensure http traffic is allowed through the firewall
          ansible.posix.firewalld:
            service: http
            state: enabled
            permanent: yes
            zone: internal
            immediate: yes
        - name: Ensure a repo directory exists
          ansible.builtin.file:
            #path: /usr/share/nginx/html/repo/BaseOS/x86_64/os/Packages
            path: /usr/share/nginx/html/repo/Packages
            state: directory
            owner: root
            group: root
            mode: "0755"
        - name: Add packages to repo
          ansible.builtin.get_url:
            url: https://download.rockylinux.org/vault/rocky/8.5/BaseOS/x86_64/os/Packages/b/bash-completion-2.7-5.el8.noarch.rpm
            dest: /usr/share/nginx/html/repo/Packages
        - name: Run createrepo on the repo directory
          command: createrepo /usr/share/nginx/html/repo
      become: yes
- name: Configure server2
  gather_facts: false
  hosts:
    - localhost
  tasks:
    - block:
        - name: Breaking something
          ansible.builtin.file:
            path: /var/cache/man/{{ item }}
            state: absent
          loop:
            - index.db
            - overrides/index.db
        - name: Breaking something
          ansible.builtin.shell: rm -f /etc/yum.repos.d/*
        - name: Breaking something
          ansible.builtin.replace:
            path: /etc/default/grub
            regexp: 'rhgb quiet.*"$'
            replace: 'rhgb quiet init=/bin/false"'
          register: grubconf
        - name: Breaking something
          ansible.builtin.command: grub2-mkconfig -o /boot/efi/EFI/rocky/grub.cfg
          when: grubconf.changed
        - name: Breaking something
          ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
          when: grubconf.changed
        - name: Breaking something
          ansible.builtin.replace:
            path: /etc/group
            regexp: '^wheel:x:10:.*$'
            replace: 'wheel:x:10:vagrant'
        - name: Breaking something
          ansible.builtin.user:
            name: root
            password: "{{ 'somerandompassword' | password_hash('sha512', 'randomsalt') }}"
        - name: Breaking something
          ansible.builtin.nmcli:
            conn_name: example_com
            state: absent
        - name: Rebooting
          ansible.builtin.command: systemctl reboot
      become: yes
