---
- name: Ensure the openvpn package is installed
  ansible.builtin.package:
    name: openvpn
    state: present
  become: yes
- name: Ensure directory for server configuration exists
  ansible.builtin.file:
    path: "/etc/openvpn/server"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes
- name: Ensure openvpn server.conf file exists
  ansible.builtin.template:
    src: server.conf.j2
    dest: "/etc/openvpn/server/server.conf"
    owner: root
    group: root
    mode: '0644'
  become: yes
- name: Ensure runit support for openvpn is installed and enabled
  ansible.builtin.include_role:
    name: runit-service
  vars:
    service:
      name: openvpn
      startcmd: "/usr/sbin/openvpn --config /etc/openvpn/server/server.conf"
      enabled: true
- name: Ensure inbound openvpn connections are allowed through firewall
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    in_interface: eth1
    ctstate: NEW
    destination: 192.168.122.0/24
    destination_port: '1194'
    protocol: udp
    jump: ACCEPT
  become: yes
- name: Ensure packets from tun interfaces are excepted
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    in_interface: tun+
    jump: ACCEPT
  become: yes
- name: Ensure traffic to 1194 is allowed through the firewall
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    in_interface: "{{ openvpn.in_interface }}"
    jump: ACCEPT
  become: yes
