---
- name: Ensure the necessary host variables have been set
  ansible.builtin.assert:
    that: user.download_dir is defined and packer.build_dir is defined
    fail_msg: |
      This role requires both user.download_dir and packer.build_dir to be
      defined.  Please ensure both of these are set in your host variables.
- name: Get the list of currently available Vagrant base boxes
  ansible.builtin.shell: set -o pipefail && vagrant box list | awk '{ print $1 }'
  args:
    executable: "{{ ansible_user_shell }}"
  changed_when: false
  register: vagrant_box_list
- name: Build the requested base boxes
  ansible.builtin.include_tasks: configurebox.yml
  vars:
    distro: "{{ this.distro }}"
    version: "{{ this.version }}"
    configuration: "{{ this.configuration }}"
    box: "{{ this.distro }}-{{ this.version }}-{{ this.configuration }}"
  loop: "{{ boxes }}"
  loop_control:
    loop_var: this
    label: "{{ box }}"
  when: box not in vagrant_box_list.stdout_lines
