---
# do one time only
- name: Assert this host can use this role
  ansible.builtin.assert:
    that: ansible_distribution in role.supported_distributions
    fail_msg: "This role is not supported on your host operating system."
- name: Ensure the packer build directories exists before copying files there
  # this is a bit hacky as it hardcodes a directory path for the Win10 box
  ansible.builtin.file:
    path: "{{ packer.build_dir }}"
    state: directory
    mode: '0700'
- name: Get the list of currently available Vagrant base boxes
  ansible.builtin.shell: set -o pipefail && vagrant box list | awk '{ print $1 }'
  args:
    executable: "{{ ansible_user_shell }}"
  changed_when: false
  register: vagrant_box_list
- name: Build the requested base boxes
  ansible.builtin.include_tasks: configurebox.yml
  vars:
    distro: "{{ this.distro }}"
    version: "{{ this.version }}"
    configuration: "{{ this.configuration }}"
    box: "{{ this.distro }}-{{ this.version }}-{{ this.configuration }}"
  loop: "{{ boxes }}"
  loop_control:
    loop_var: this
    label: "{{ box }}"
  when: box not in vagrant_box_list.stdout_lines
