---
- hosts: localhost
  tasks:
    - name: Ensure this playbook is being run on server2
      ansible.builtin.assert:
        that:
          - ansible_hostname == "server2"
        fail_msg: 'This playbook must be run on server2.'
        quiet: yes
    - name: Ensure firewall service is started
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      become: yes
    - name: Ensure firewall allows http traffic
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
        zone: internal
      loop:
        - mountd
        - nfs
        - rpc-bind
      become: yes
