# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # These are the VM configuration defaults when not overridden
  config.ssh.private_key_path = "~/keys/vagrant"
  config.vm.box = "CentOS-7.0-1406-x86_64-Minimal"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    #ansible.groups = {
    #  "ipa-client" => ["server1","server2","testnetinstall"],
    #  "ipa-server" => ["labipa"]
    #}
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.gui = true
    vb.customize ["modifyvm", :id, "--ostype", "RedHat_64"]
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.customize ["modifyvm", :id, "--nic2", "natnetwork",
                                   "--nictype2", "82540EM",
                                   "--cableconnected2", "on",
                                   "--nicpromisc2", "allow-vms",
                                   "--nat-network2", "RHCSA"]
    vb.customize ["modifyvm", :id, "--boot1", "dvd"]
    vb.customize ["modifyvm", :id, "--boot2", "disk"]
    vb.customize ["modifyvm", :id, "--boot3", "none"]
    vb.customize ["modifyvm", :id, "--boot4", "none"]
    vb.customize ["modifyvm", :id, "--vram", "16"]
    vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    vb.customize ["modifyvm", :id, "--vrde", "off"]
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["storageattach", :id, "--storagectl", "IDE Controller",
                                        "--port", 0,
                                        "--device", 1,
                                        "--type", "dvddrive",
                                        "--medium", "emptydrive"]
  end
  
  #=== router ===
  config.vm.define "router" do |node|
    node.vm.hostname = "router.example.com"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "router"
      vb.customize ["modifyvm", :id, "--nic3", "natnetwork",
                                     "--nictype3", "82540EM",
                                     "--cableconnected3", "on",
                                     "--nicpromisc3", "allow-vms",
                                     "--nat-network3", "RHCSA2"]
    end
  end

  #=== rhcsa1 ===
  config.vm.define "rhcsa1" do |node|
    node.vm.box = "CentOS-7.4-1708-x86_64-Minimal"
    node.vm.hostname = "rhcsa1.example.com"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "rhcsa1"
    end
  end

  #=== rhcsa2 ===
  config.vm.define "rhcsa2" do |node|
    node.vm.hostname = "rhcsa2.example.com"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "rhcsa2"
      vb.customize ["modifyvm", :id, "--nat-network2", "RHCSA2"]
    end
  end
end
