# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.private_key_path= "~/keys/vagrant"
  config.vm.box = "ubuntu-15.10-server-amd64"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
  SHELL
end
