---
- name: Ensure the nginx package is installed
  ansible.builtin.package:
    name: nginx
    state: present
  become: yes
- name: Ensure runit support for nginx is installed and enabled
  ansible.builtin.include_role:
    name: runit-service
  vars:
    service:
      name: nginx
      startcmd: "/usr/sbin/nginx -g 'daemon off;'"
      enabled: true
