---
- hosts: localhost
  tasks:
    - name: Ensure this playbook is being run on server2
      ansible.builtin.assert:
        that:
          - ansible_hostname == "server2"
        fail_msg: 'This playbook must be run on server2.'
        quiet: yes
    - name: Doing something...
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      become: yes
    - name: Doing something...
      ansible.builtin.command: firewall-cmd --set-default-zone=home
      become: yes
    - name: Doing something...
      ansible.posix.firewalld:
        interface: enp0s3
        state: enabled
        immediate: yes
        permanent: yes
        zone: public
      become: yes
    - name: Doing something...
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: no
      become: yes
