# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # These are the VM configuration defaults when not overridden
  config.ssh.private_key_path = "~/keys/vagrant"
  config.vm.box = "CentOS-7.4-1708-x86_64-ServerWithGUI"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    #ansible.groups = {
    #  "ipa_client" => ["server1","server2","testnetinstall"],
    #  "ipa_server" => ["labipa"]
    #}
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.gui = true
    vb.customize ["modifyvm", :id, "--ostype", "RedHat_64"]
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.customize ["modifyvm", :id, "--nic2", "natnetwork",
                                   "--nictype2", "82540EM",
                                   "--cableconnected2", "on",
                                   "--nicpromisc2", "allow-vms",
                                   "--nat-network2", "RHCSA"]
    vb.customize ["modifyvm", :id, "--boot1", "dvd"]
    vb.customize ["modifyvm", :id, "--boot2", "disk"]
    vb.customize ["modifyvm", :id, "--boot3", "none"]
    vb.customize ["modifyvm", :id, "--boot4", "none"]
    vb.customize ["modifyvm", :id, "--vram", "16"]
    vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    vb.customize ["modifyvm", :id, "--vrde", "off"]
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["storageattach", :id, "--storagectl", "IDE Controller",
                                        "--port", 0,
                                        "--device", 1,
                                        "--type", "dvddrive",
                                        "--medium", "emptydrive"]
  end
  
  #=== installserver ===
  config.vm.define "installserver" do |node|
    node.vm.box = "CentOS-7.4-1708-x86_64-Minimal"
    node.vm.hostname = "installserver.example.com"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "installserver"
    end
  end

  #=== workstation ===
  config.vm.define "workstation" do |node|
    node.vm.hostname = "workstation.example.com"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "workstation"
      vb.memory = 2048
    end
  end
end
