#!/bin/bash
echo "Please shutdown any VMs and make sure VirtualBox is not running before you continue."
read -p "Press enter to continue." a

for d in VBoxDrv VBoxUSB VBoxNetFlt VBoxNetAdp; do
  sudo /usr/bin/kmutil unload -b org.virtualbox.kext.$d 2> /dev/null
  sudo /usr/bin/kmutil load -b org.virtualbox.kext.$d
  echo -n "$d: "
  kmutil showloaded -V release --collection aux --list-only | grep -q $d
  if [ $? -eq 0 ]; then
    echo "OK"
  else
    echo "Not loaded"
  fi
done
