# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "Ubuntu Desktop 64-bit 15.04"

  config.ssh.private_key_path= "/Users/demouser/vm/keys/vagrant"

  config.vm.network "private_network", ip: "192.168.56.100", virtualbox__hostonly: true

  config.vm.synced_folder "../../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "workstation"
    # vb.memory = "1024"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    # sudo apt-get install -y apache2
  SHELL
end
