---
supported_distributions:
  - MacOSX
  - Debian
  - Fedora
download_dir: "{{ ansible_user_dir }}/Downloads"
# =================
# Software versions
# =================
# defaults for GNS3
gns3_vers: "2.2"
gns3_version: "2.2.33.1"
gns3_dmg_checksum:  "sha256:dc83078e80717ccc2d74929374e07162aa884b08743d81b28a66711f5b2d5686"
gns3_user_dir: "{{ ansible_user_dir }}/GNS3"
gns3_config_dir: "{{ ansible_user_dir }}/.config/GNS3/{{ gns3_vers }}"
# defaults for GNS3.VM for VirtualBox
gns3vm_vbox_zip: "GNS3.VM.VirtualBox.{{ gns3_version }}.zip"
gns3vm_vbox_zip_url: "https://github.com/GNS3/gns3-gui/releases/download/v{{ gns3_version }}/{{ gns3vm_vbox_zip }}"
gns3vm_vbox_zip_checksum: "sha256:a8e98d559bfbaaf1fa43bdec4cb35d19bb9b77801914801ad6bca18f76a237bb"
# vars for gns3_controller.j2
g3controller_gns3vm_vmname: "GNS3 VM"
g3controller_gns3vm_headless: "true"
g3controller_gns3vm_enable: "true"
g3controller_gns3vm_engine: "virtualbox"
g3controller_gns3vm_ram: 4096
g3controller_gns3vm_vcpus: 2

# vars for gns3_gui.j2
g3gui_mainwindow_check_for_update: "false"
g3gui_mainwindow_hdpi: "false"
# vars for gns3_server.j2
g3server_server_host: "192.168.56.1"
