---
- name: Assert this host can use this role
  assert:
    that: ansible_distribution in supported_distributions
    fail_msg: "This role is not supported on your host operating system."
- name: Include host distribution specific variables
  include_vars: "{{ ansible_distribution | lower }}.yml"
- name: role packages
  include_tasks: "packages-{{ ansible_distribution | lower }}.yml"
# The path below may change when we go back to homebrew
- name: Ensure ubridge ownership and permissions are correct
  file:
    path: /Applications/GNS3.app/Contents/MacOS/ubridge
    state: file
    owner: "root"
    group: "admin"
    mode: "04750"
  become: yes
  when: ansible_distribution == "MacOSX"
- name: Ensure the GNS3 server VM is installed
  include_tasks: "gns3vm-packages-{{ ansible_distribution | lower }}.yml"
- name: Ensure LaunchAgents directory exists
  file:
    path: "{{ ansible_user_dir }}/Library/LaunchAgents"
    state: directory
    mode: '0755'
- name: Ensure there is a directory for the vboxnet LaunchAgent logs
  file:
    path: "{{ ansible_user_dir }}/.vboxnet"
    state: directory
- name: Ensure the script to start vboxnet at login is installed
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "vboxnet.zsh", dest: "{{ ansible_user_dir }}/.vboxnet/vboxnet.zsh", mode: '0755' }
    - { src: "com.user.loginscript.plist", dest: "{{ ansible_user_dir }}/Library/LaunchAgents/com.user.loginscript.plist", mode: '0644' }
- name: Ensure GNS3 configuration directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/GNS3/{{ gns3_vers }}"
    state: directory
    mode: '0755'
- name: Test if gns3_controller.conf exists
  stat:
    path: "{{ ansible_user_dir }}/.config/GNS3/{{ gns3_vers }}/gns3_controller.conf"
  changed_when: false
  register: gns3_controller
- name: Ensure default gns3_controller.conf is installed when none exists
  template:
    src: gns3_controller.j2
    dest: "{{ ansible_user_dir }}/.config/GNS3/{{ gns3_vers }}/gns3_controller.conf"
    mode: '0644'
  when: not gns3_controller.stat.exists
- name: Test if gns3_server.conf exists
  stat:
    path: "{{ ansible_user_dir }}/.config/GNS3/{{ gns3_vers }}/gns3_server.conf"
  changed_when: false
  register: gns3_server
- name: Ensure default gns3_server.conf is installed when none exists
  template:
    src: gns3_server.j2
    dest: "{{ ansible_user_dir }}/.config/GNS3/{{ gns3_vers }}/gns3_server.conf"
    mode: '0644'
  when: not gns3_server.stat.exists
- name: Test if gns3_gui.conf exists
  stat:
    path: "{{ ansible_user_dir }}/.config/GNS3/{{ gns3_vers }}/gns3_gui.conf"
  changed_when: false
  register: gns3_gui
- name: Ensure default gns3_gui.conf is installed when none exists
  template:
    src: gns3_gui.j2
    dest: "{{ ansible_user_dir }}/.config/GNS3/{{ gns3_vers }}/gns3_gui.conf"
    mode: '0644'
  when: not gns3_gui.stat.exists
- name: Ensure obsolete files have been cleaned up
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/.vboxnet0.zsh"
    - "{{ ansible_user_dir }}/setenv.QT_MAC_WANTS_LAYER.plist"
- name: Ensure workaround for PyQt5 bug is installed
  copy:
    dest: "{{ ansible_user_dir }}/Library/LaunchAgents/setenv.QT_MAC_WANTS_LAYER.plist"
    src: "setenv.QT_MAC_WANTS_LAYER.plist"
    mode: "0644"
  register: qtmacenv
- name: Notify user the about the need to reboot
  block:
    - name: Display message to reboot if environment changed
      fail:
        msg: "This playbook has updated the environment.  Please reboot when it finishes so the changes take effect."
      ignore_errors: true
    - name: Speak message to reboot if environment changed
      command: say "This playbook has updated the environment.  Please reboot when it finishes so the changes take effect."
  when: qtmacenv.changed
