# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Common to all VMs
  config.ssh.private_key_path= "~/vm/keys/vagrant"
  config.vm.box = "ubuntu-15.10-server-amd64"
  config.vm.synced_folder "~/vm/data", "/vagrant_data"
  config.vm.boot_timeout = 60

  # Loop for VM specific config
  (50..52).each do |vmNum|
    config.vm.define "vm#{vmNum}" do |node|
      node.vm.network "private_network", ip: "192.168.2.#{vmNum}", virtualbox__null: true
      node.vm.provider "virtualbox" do |vb|
        vb.name = "vm#{vmNum}"
      end
      node.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "ansible/playbook.yml"
        ansible.groups = {
          "nameservers" => ["vm50"],
          "dhcpservers" => ["vm51"],
          "gateway" => ["vm52"],
        }
      end
    end
  end
end
