---
- name: Ensure Server With GUI environment is installed
  ansible.builtin.dnf:
    name: "@Server with GUI"
    state: present
  become: yes
- name: Ensure default systemd target is graphical
  ansible.builtin.command: "systemctl set-default graphical.target"
  become: yes
  notify:
    - start_gui
- name: Ensure vagrant user is hidden from gdm login screen
  ansible.builtin.copy:
    src: vagrant
    dest: /var/lib/AccountsService/users
    mode: '0600'
  become: yes
  when: "'servers_with_gui' in group_names"
