---
# tasks file for coursematerials
- name: Include course specific variables for {{ course }}
  include_vars: "{{ course }}.yml"
- name: Ensure course root exists
  file:
    path: "{{ courseroot }}{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/"
    - "/images"
- name: Ensure common images exist
  copy:
    src: "{{ item }}"
    dest: "{{ courseroot }}/images"
    mode: '0644'
  loop:
    - 'ConstructionSign.png'
- name: Ensure directories exist for each chapter
  include_tasks: make-chapter.yml
  loop: "{{ study_guide.chapters }}"
  loop_control:
    loop_var: chapter
    index_var: chapter_num
- name: Ensure a schedule template CSV file exists
  template:
    src: "schedule-template.j2"
    dest: "{{ courseroot }}/{{ schedulefile }}"
    mode: '0644'
