---
- name: Ensure Samba server and client is installed
  ansible.builtin.yum:
    name: [samba, samba-client, samba-common-tools]
    state: present
  become: yes
- name: Ensure host-specific shares have been configured
  ansible.builtin.include_tasks: add-samba-share.yml
  loop: "{{ service.samba.shares }}"
  loop_control:
    loop_var: share
    label: "{{ share.sharename }}"
  when: service.samba.shares is defined
- name: Ensure Samba systemd service is configured
  ansible.builtin.service:
    name: smb
    state: "{{ service.samba.state }}"
    enabled: "{{ service.samba.enabled }}"
  become: yes
- name: Ensure Samba traffic is allowed through firewall
  ansible.builtin.firewalld:
    service: "{{ item }}"
    state: "{{ service.samba.fw_state }}"
    permanent: "{{ service.samba.fw_permanent }}"
    immediate: "{{ service.samba.fw_immediate }}"
    zone: "{{ service.samba.fw_zone }}"
  loop:
    - samba
    - samba-client
  become: yes
- name: Get a list of Samba users that already exist in tdbsam database
  ansible.builtin.shell: pdbedit -L | cut -f1 -d':'
  become: yes
  register: pdbedit
  changed_when: false
  when:
    - service.samba.smbusers is defined
    - ( service.samba.smbusers | length > 0)
- name: Ensure missing SMB user accounts are created
  ansible.builtin.include_tasks: smbuser-add.yml
  loop: "{{ service.samba.smbusers }}"
  loop_control:
    loop_var: smbuser
    label: "{{ smbuser.name }}"
  when:
    - pdbedit.stdout is defined
    - smbuser.name not in pdbedit.stdout
