---
- name: Configure server2
  gather_facts: false
  hosts:
    - localhost
  tasks:
    #- name: Ensure SELinux is in permissive mode
    #  ansible.posix.selinux:
    #    policy: targeted
    #    state: permissive
    #  become: yes
    - name: Breaking something...
      user:
        name: student
        password: "{{ 'somerandompassword' | password_hash('sha512', 'randomsalt') }}"
      become: yes
    - name: Breaking something...
      shell: usermod -G $(id -nG student | sed -e 's/ /,/' -e 's/,wheel//') student
      become: yes
    - ansible.builtin.command: systemctl reboot
      become: yes
