#!/bin/bash
VAGRANT_VERSION=2.2.4
if [[ ! -d "$HOME/.ssh" ]]; then
  mkdir -m 700 "$HOME/.ssh"
fi
if [[ ! -f "$HOME/.ssh/google_compute_engine" ]]; then
  cat <<DONE
=== NOTICE: Unable to find a keypair for passwordless SSH ===
We were unable to find the keypair Vagrant uses to authenticate to
virtual machines in GCP.

DONE
read -p "Press enter to generate a new key (leave the passphrase empty)."
  ssh-keygen -b 2048 -f "$HOME/.ssh/google_compute_engine"
  cat <<DONE

A new keypair was created but you still need to tell GCP to add the
public key to the authorized_hosts file within each virtual machine.

Please log into console.cloud.google.com and go to
Compute Engine > Metadata > SSH Keys > Edit.  From there, click Add
item and paste this key, being careful to paste it as a single line
without line breaks:

DONE
  cat $HOME/.ssh/google_compute_engine.pub
  cat <<DONE

Once you have completed the steps above, press return to continue.
DONE
  read a
fi
if [[ ! -x /usr/bin/rsync ]]; then
  sudo apt-get install -y rsync
fi
if [[ ! -f /usr/bin/vagrant ]]; then
  if [[ ! -f vagrant_${VAGRANT_VERSION}_x86_64.deb ]]; then
    wget https://releases.hashicorp.com/vagrant/$VAGRANT_VERSION/vagrant_${VAGRANT_VERSION}_x86_64.deb
  fi
  sudo dpkg -i vagrant_${VAGRANT_VERSION}_x86_64.deb
fi
vagrant plugin list | grep -q vagrant-google
if [[ $? -ne 0 ]]; then
  vagrant plugin install vagrant-google
fi
if [[ ! -f Vagrantfile.gcp ]]; then
  cat > Vagrantfile.gcp <<DONE
Vagrant.configure("2") do |config|
  config.vm.box = "google/gce"
  config.vm.synced_folder "labfiles/", "/labfiles", type: "rsync", rsync__exclude: ".git/"

  config.vm.provider :google do |google, override|
    google.google_project_id = "$GOOGLE_CLOUD_PROJECT"
    google.google_json_key_location = "$HOME/.ssh/key.json"
    
    google.image_family = 'centos-7'
    
    override.ssh.username = "$USER"
    override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end

end
DONE
fi
cat <<DONE
============================
=    Setup is complete.    =
============================
First, make sure Vagrantfile is a symbolic link to Vagrantfile.gcp.
Then you can run:

  vagrant up

to create the virtual machines in GCP.

DONE
