# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # These are the VM configuration defaults when not overridden
  config.ssh.private_key_path = "~/keys/vagrant"

  config.vm.box = "CentOS-7.5-1804-x86_64-ServerWithGui"
  config.vm.synced_folder ".", "/vagrant", disabled: true
#  config.vm.synced_folder "labfiles/",
#                          "/labfiles",
#                          type: "nfs",
#                          nfs_version: 4,
#                          nfs_udp: false,
#                          nfs: true,
#                          mount_options: ["rw", "vers=4", "tcp", "async", "_netdev", "noatime"]
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/vagrant-vm-playbook.yml"
    ansible.groups = {
      "ipa-client" => ["server1","server2","testnetinstall"],
      "ipa-server" => ["labipa"]
    }
  end

  #config.vm.provider "qemu" do |vb|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.host = "localhost"
    libvirt.uri = 'qemu:///system'
  end
  
  #=== labipa ===
  config.vm.define "labipa" do |node|
    node.vm.network :private_network,
      :type => "dhcp",
      :libvirt__network_name => "vagrant-private-dhcp",
      :libvirt__domain_name => "example.com",
      :libvirt__network_address => "192.168.4.0",
      :libvirt__netmask => "255.255.255.0",
      :libvirt__dhcp_enabled => true,
      :libvirt__host_ip => "192.168.4.1",
      :libvirt__dhcp_start => "192.168.4.2",
      :libvirt__dhcp_stop => "192.168.4.99"
    node.vm.provider "qemu" do |vb|
      vb.name = "labipa"
      vb.memory = 2048
      vb.gui = true
    end
  end

  #=== server1 ===
  config.vm.define "server1" do |node|
    node.vm.provider "qemu" do |vb|
      vb.name = "server1"
    end
  end 
  
  #=== server2 ===
  config.vm.define "server2" do |node|
    node.vm.box = "CentOS-7.5-1804-x86_64-Minimal"
    node.vm.provider "qemu" do |vb|
      vb.name = "server2"
#      vb.customize ["modifyvm", :id, "--nic3", "natnetwork",
#                                     "--nictype3", "82540EM",
#                                     "--cableconnected3", "on",
#                                     "--nicpromisc3", "allow-vms",
#                                     "--nat-network3", "RHCxNetwork"]
#      vb.customize ["modifyvm", :id, "--nic4", "natnetwork",
#                                     "--nictype4", "82540EM",
#                                     "--cableconnected4", "on",
#                                     "--nicpromisc4", "allow-vms",
#                                     "--nat-network4", "RHCxNetwork"]
    end
  end
  
  #=== testnetinstall ===
  config.vm.define "testnetinstall", autostart: false do |node|
    node.vm.box = "CentOS-7.0-1406-x86_64-Minimal"
    node.vm.provider "qemu" do |vb|
      vb.name = "testnetinstall"
    end
  end
end
