# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # These are the VM configuration defaults when not overridden
  config.ssh.private_key_path = "~/keys/vagrant"
  config.vm.box = "CentOS-7-x86_64-ServerWithGUI"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "labfiles/", "/labfiles"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/vagrant-vm-playbook.yml"
    ansible.groups = {
      "ipa-client" => ["server1","server2","testnetinstall"],
      "ipa-server" => ["labipa"]
    }
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.gui = true
    vb.customize ["modifyvm", :id, "--ostype", "RedHat_64"]
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.customize ["modifyvm", :id, "--nic2", "natnetwork",
                                   "--nictype2", "82540EM",
                                   "--cableconnected2", "on",
                                   "--nicpromisc2", "allow-vms",
                                   "--nat-network2", "RHCxNetwork"]
    vb.customize ["modifyvm", :id, "--boot1", "dvd"]
    vb.customize ["modifyvm", :id, "--boot2", "disk"]
    vb.customize ["modifyvm", :id, "--boot3", "none"]
    vb.customize ["modifyvm", :id, "--boot4", "none"]
    vb.customize ["modifyvm", :id, "--vram", "16"]
    vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    vb.customize ["modifyvm", :id, "--vrde", "off"]
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["storageattach", :id, "--storagectl", "IDE Controller",
                                        "--port", 0,
                                        "--device", 1,
                                        "--type", "dvddrive",
                                        "--medium", "emptydrive"]
  end
  
  #=== labipa ===
  config.vm.define "labipa" do |node|
    node.vm.provider "virtualbox" do |vb|
      vb.name = "labipa"
      vb.memory = 2048
    end
  end

  #=== server1 ===
  config.vm.define "server1" do |node|
    node.vm.provider "virtualbox" do |vb|
      vb.name = "server1"
    end
  end 
  
  #=== server2 ===
  config.vm.define "server2" do |node|
    node.vm.box = "CentOS-7-x86_64-Minimal"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "server2"
      vb.customize ["modifyvm", :id, "--nic3", "natnetwork",
                                     "--nictype3", "82540EM",
                                     "--cableconnected3", "on",
                                     "--nicpromisc3", "allow-vms",
                                     "--nat-network3", "RHCxNetwork"]
      vb.customize ["modifyvm", :id, "--nic4", "natnetwork",
                                     "--nictype4", "82540EM",
                                     "--cableconnected4", "on",
                                     "--nicpromisc4", "allow-vms",
                                     "--nat-network4", "RHCxNetwork"]
    end
  end
  
  #=== testnetinstall ===
  config.vm.define "testnetinstall", autostart: false do |node|
    node.vm.box = "CentOS-7-x86_64-Minimal"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "testnetinstall"
    end
  end
end
