---
- name: Ensure {{ ansible_user_dir }}/.bashrc exists
  file:
    path: "{{ ansible_user_dir }}/.bashrc"
    state: file
- name: Ensure convenience functions are defined
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |
      export VAGRANT_DEFAULT_PROVIDER=libvirt
      build () {
        vagrant up --no-parallel $1
      }
      rebuild () {
        vagrant destroy -f $1
        vagrant up --no-parallel $1
      }
      showlabs () {
        find ~/demo/rhcx/labfiles/lab* -name "README*" -exec head -1 \{\} \;
      }
